package com.discovery.darchrow.single.model;

import java.io.Serializable;

public class User implements Serializable{
	
	
    /** */
	private static final long serialVersionUID = 3132145589745062105L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.user_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String password;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    

}