package com.discovery.darchrow.single.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
	
	
    /** */
	private static final long serialVersionUID = 3132145589745062105L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.user_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.status
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.create_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.update_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.real_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.first_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.last_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.email
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.mobile
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.phone
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.description
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.avatar
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.store_id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.pwd_change_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Date pwdChangeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.last_password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String lastPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.pwd_error_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Integer pwdErrorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.last_login_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_au_user.last_login_ip
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    private String lastLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.id
     *
     * @return the value of t_au_user.id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.id
     *
     * @param id the value for t_au_user.id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.user_name
     *
     * @return the value of t_au_user.user_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.user_name
     *
     * @param userName the value for t_au_user.user_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.password
     *
     * @return the value of t_au_user.password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.password
     *
     * @param password the value for t_au_user.password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.status
     *
     * @return the value of t_au_user.status
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.status
     *
     * @param status the value for t_au_user.status
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.create_time
     *
     * @return the value of t_au_user.create_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.create_time
     *
     * @param createTime the value for t_au_user.create_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.update_time
     *
     * @return the value of t_au_user.update_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.update_time
     *
     * @param updateTime the value for t_au_user.update_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.real_name
     *
     * @return the value of t_au_user.real_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.real_name
     *
     * @param realName the value for t_au_user.real_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.first_name
     *
     * @return the value of t_au_user.first_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.first_name
     *
     * @param firstName the value for t_au_user.first_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.last_name
     *
     * @return the value of t_au_user.last_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.last_name
     *
     * @param lastName the value for t_au_user.last_name
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.email
     *
     * @return the value of t_au_user.email
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.email
     *
     * @param email the value for t_au_user.email
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.mobile
     *
     * @return the value of t_au_user.mobile
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.mobile
     *
     * @param mobile the value for t_au_user.mobile
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.phone
     *
     * @return the value of t_au_user.phone
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.phone
     *
     * @param phone the value for t_au_user.phone
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.description
     *
     * @return the value of t_au_user.description
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.description
     *
     * @param description the value for t_au_user.description
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.avatar
     *
     * @return the value of t_au_user.avatar
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.avatar
     *
     * @param avatar the value for t_au_user.avatar
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.store_id
     *
     * @return the value of t_au_user.store_id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.store_id
     *
     * @param storeId the value for t_au_user.store_id
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.pwd_change_time
     *
     * @return the value of t_au_user.pwd_change_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Date getPwdChangeTime() {
        return pwdChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.pwd_change_time
     *
     * @param pwdChangeTime the value for t_au_user.pwd_change_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setPwdChangeTime(Date pwdChangeTime) {
        this.pwdChangeTime = pwdChangeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.last_password
     *
     * @return the value of t_au_user.last_password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getLastPassword() {
        return lastPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.last_password
     *
     * @param lastPassword the value for t_au_user.last_password
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setLastPassword(String lastPassword) {
        this.lastPassword = lastPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.pwd_error_time
     *
     * @return the value of t_au_user.pwd_error_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Integer getPwdErrorTime() {
        return pwdErrorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.pwd_error_time
     *
     * @param pwdErrorTime the value for t_au_user.pwd_error_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setPwdErrorTime(Integer pwdErrorTime) {
        this.pwdErrorTime = pwdErrorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.last_login_time
     *
     * @return the value of t_au_user.last_login_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.last_login_time
     *
     * @param lastLoginTime the value for t_au_user.last_login_time
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_au_user.last_login_ip
     *
     * @return the value of t_au_user.last_login_ip
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_au_user.last_login_ip
     *
     * @param lastLoginIp the value for t_au_user.last_login_ip
     *
     * @mbggenerated Wed Nov 30 18:36:06 CST 2016
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }
}